[package]
name = "benqi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "benqi"
path = "substance.rs"

[dependencies]
book = { path = "../../../libs/book" }
data_entry = { path = "../" }
