[package]
name = "gecko"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gecko"
path = "../quizzes/quiz09/answer09.rs"

[dependencies]
book = { path = "../../libs/book" }
swerve = { path = "../swerve" }

tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
