[package]
name = "one_line"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "one_line"
path = "one_line.rs"

[dependencies]
book = { path = "../../libs/book" }
