[package]
name = "lizard"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lizard"
path = "../quizzes/quiz19/answer19b_merged_prices.rs"

[dependencies]
book = { path = "../../libs/book" }
swerve = { path = "../swerve" }

tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
