// common functions to generate reports

use crate::{
   csv_utils::CsvWriter,
   html_utils::{a,ol,p,h,Mode,roff,proff}
};

// ----- FOOTERS -------------------------------------------------------

pub fn print_footer(mode: Mode, src_dir: &str, program: &str) {
   let repo = "https://github.com/logicalgraphs/crypto-n-rust/blob/main";
   let source = format!("{src_dir}/{program}.rs");
   let url = format!("{repo}/{source}");
   let prelude = "Report generated by";
   let prog = format!("./{program}");
   let sub_url = roff(&mode, &a(&url, &prog));
   proff(mode)(p(&format!("{prelude} {sub_url}")));
}

pub fn print_message(mode: Mode, mesg: &str) {
   proff(mode)(p(mesg));
}

// ----- HEADERS -------------------------------------------------------

pub fn print_top<T: CsvWriter + Clone>(n: usize, title: &str, date: &str, 
                                       lps: &[T], mode: Mode) {
   let mut new_lps: Vec<T> = Vec::new();
   let mut x = 1;
   for b in lps {
      if x > n { break; }
      new_lps.push(b.clone());
      x += 1;
   }
   print_top_of(title, date, &new_lps, mode);
}

pub fn print_top_by<T: CsvWriter + Clone>(f: impl FnMut(&T) -> bool, 
      title: &str, date: &str, lps: &[T], mode: Mode) {
   let mut new_lps: Vec<T> = lps.to_vec();
   new_lps.retain(f);
   print_top_of(title, date, &new_lps, mode);
}

pub fn print_top_of<T: CsvWriter>(title: &str, date: &str, lps: &[T], 
      mode: Mode) {
   let n = lps.len();
   let header = format!("Top {n} {title}, {date}");
   proff(mode.clone())(h(2, &header));
   let stringy: Vec<String> = lps.iter().map(|a| a.as_csv()).take(n).collect();
   proff(mode)(ol(&stringy));
}

// ----- TESTS -------------------------------------------------------

#[cfg(test)]
#[cfg(not(tarpaulin_include))]
mod functional_tests {
   use super::*;
   use paste::paste;
   use crate::{
      create_testing,
      err_utils::ErrStr,
      html_utils::Mode::HTML,
      types::dyadic::mk_dyad
   };

   create_testing!("report_utils");

   run!("print_footer", print_footer(HTML, "dApps", "gecko"));
   run!("print_top", print_top(5, "Titlist", "2026-06-18",
        &[mk_dyad("foo", "bar", 12), mk_dyad("baz", "quux", 314)], HTML));
}

