[package]
name = "voronoi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "lib.rs"

[[bin]]
name = "voronoi"
path = "voronoi.rs"

[dependencies]
book = { path = "../../../libs/book" }
crypto = { path = "../../../libs/crypto" }
rand = "0.9.0-alpha.0"
