[package]
name = "answer06"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "answer06"
path = "answer06_local.rs"

[dependencies]
book = { path = "../../../libs/book" }
crypto = { path = "../../../libs/crypto" }

serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
