[package]
name = "stamp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "despace"
path = "despace.rs"

[dependencies]
book = { path = "../../libs/book" }
chrono = "0.4.22"
