[package]
name = "pivot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "quiz02"
path = "quiz02.rs"

[dependencies]
book = { path = "../../../../libs/book" }
swerve = { path = "../../swerve" }
