[package]
name = "data_entry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "data_entry"
path = "../data_entry.rs"

[dependencies]
book = { path = "../../libs/book" }
