[package]
name = "real_apy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "real_apy"
path = "real_apy.rs"

[dependencies]
book = { path = "../../libs/book" }
