[package]
name = "answer05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "answer05"
path = "answer05.rs"

[dependencies]
book = { path = "../../../libs/book" }
swerve = { path = "../../swerve" }
