[package]
name = "apy_goal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
book = { path = "../../libs/book" }

[[bin]]
name = "apy_goal"
path = "apy_goal.rs"
