[package]
name = "price_quotes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "price_quotes"
path = "price_quotes.rs"

[dependencies]
book = { path = "../../libs/book" }
