[package]
name = "cmc_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cmc_filter"
path = "src/cmc_filter.rs"

[lib]
name = "cmc_filter"
path = "src/lib.rs"
