[package]
name = "percs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "percs"
path = "percs.rs"

[dependencies]
crypto = { path = "../../libs/crypto" }
