name: coffee

on:
  workflow_dispatch:
  schedule:
    # test the cron at scheduled time
      - cron: "25 12 * * *"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Log Output
        run: cargo run --bin coffee >> crypto-n-rust/data-files/covfefe.txt
        
