name: coffee

on:
  workflow_dispatch:
  schedule:
    # test the cron at scheduled time
      - cron: "35 20 * * *"

jobs:
  job_0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run coffee.rs
        run: cargo run --bin coffee

  job_1:
    scheduled-job:
      runs-on: ubuntu-latest
      steps:
        - uses: [actions/checkout@v4](https://github.com)
        - name: Run Rust program and save output to file
          run: |
            ./.github/workflows/coffee.yml >> covfefe.txt
          shell: bash
        
