name: date
on:
  workflow_dispatch: 

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run The Echo and Display The Date
        run: echo "LE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV


