name: date
on:
  workflow_dispatch: 

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run The Echo & Display The Date
        env: 
          LE_DATE: ${ `date +%Y-%m-%d` }
        run: echo "This is today's date $LE_DATE!"
