name: Scheduled Workflow
on:
  schedule:
    - cron: "30 11 * * *"
jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Perform scheduled task
        run: echo "This is our first automation workflow, Prism-Man!"
