name: quotes
 
on:
  workflow_dispatch:
  schedule:
    # test the cron ("Min Hour Day Month DayofWeek" in UTC) at scheduled time 
    - cron: "37 02 * * *" # this is 10:37 AM Eastern Standard Time

permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache a_quotes binary
        id: a-quotes-cache
        uses: actions/cache@v3
        with:
          path: src/pivot/dApps/gecko/target/debug/a_quotes
          key: a-quotes-binary-${{ hashFiles('src/pivot/dApps/gecko/**/*.rs', 'src/pivot/dApps/gecko/Cargo.toml') }}

      - name: Install Rust toolchain
        if: steps.a-quotes-cache.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@stable

      - name: Build a_quotes
        if: steps.a-quotes-cache.outputs.cache-hit != 'true'
        run: cargo build --manifest-path src/pivot/dApps/gecko/Cargo.toml --bin a_quotes

      - name: Add a_quotes to PATH
        run: echo "$GITHUB_WORKSPACE/src/pivot/dApps/gecko/target/debug" >> $GITHUB_PATH
 
      - name: Run The Echo and Display The Date
        run: echo "LE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Cargo run and Log Output
        env:
          COIN_GECKO_API_KEY: ${{ secrets.COIN_GECKO_API_KEY }}
        run: a_quotes $LE_DATE >> data-files/csv/quotes.csv
        
      - name: Commit and Push changes
        env:
          USER1_NAME: ${{ vars.USER1_NAME }}
          USER1_EMAIL: ${{ secrets.USER1_EMAIL }}
        run: |
          git config --local user.email "$USER1_EMAIL"
          git config --local user.name "$USER1_NAME"
          git add data-files/csv/quotes.csv
          git commit -m "Quotes for $LE_DATE"
          git push
