name: PW_EMAIL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use secret as an environment variable
        run: |
          echo "I Have A Secret, Do Not Tell! ${{ secrets.PW_EMAIL }}"
          # Access the secret using the environment variable name
        env:
          # Map the GitHub secret to an environment variable name (e.g., PW_EMAIL)
          git config --local user.email: ${{ secrets.PW_EMAIL }} 

