name: PW_EMAIL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use secret as an environment variable
        env:
          # Map the GitHub secret to an environment variable name (e.g., PW_EMAIL)
          PW_EMAIL: ${{ secrets.PW_EMAIL }} 

        run: |
            git config --local user.email "${{ secrets.PW_EMAIL }}"
            echo "I Have A Secret, Do Not Tell! $PW_EMAIL - oopies!"
            # Access the secret using the environment variable name
            ./github/workflows/secrets.yml 

